import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const config = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    rules: {
      // Unused code is either a mistake or a leftover. Arguments prefixed with
      // an underscore are the escape hatch for the deliberate cases.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // Data crossing the Gmail and model boundaries is genuinely unknown, so
      // `any` is warned rather than forbidden — but it should be argued for.
      "@typescript-eslint/no-explicit-any": "warn",
      "prefer-const": "error",
      "no-var": "error",
      eqeqeq: ["error", "smart"],
      // console.error is how server routes report failures; the rest is debris.
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // Generated by shadcn, not hand-maintained here.
      "src/components/ui/**",
    ],
  },
];

export default config;
